import type { LmsGrant, LmsReviewEvent } from '@/lib/lms-types';
export type CourseRow = {
  id: string;
  title: string;
  summary: string;
  version: string;
  published: number;
  revision: number;
  position: number;
  price_id: string | null;
};
export type LessonRow = {
  id: string;
  course_id: string;
  title: string;
  summary: string;
  section: string;
  position: number;
  body: string;
  version: string;
  stream_uid: string | null;
  video_asset_ids: string;
  published: number;
  revision: number;
  updated_at: number;
};
export type VersionRow = {
  id: string;
  lesson_id: string;
  version: string;
  body: string;
  stream_uid: string | null;
  snapshot_json: string | null;
  created_at: number;
  created_by: string | null;
};
export type TicketRow = {
  id: string;
  user_id: string;
  title: string;
  body: string;
  lesson_id: string | null;
  course_id: string | null;
  submission_id: string | null;
  video_position: number | null;
  video_asset_id: string | null;
  status: string;
  assigned_to: string | null;
  revision: number;
  created_at: number;
  updated_at: number;
  course_title?: string;
  name?: string;
  email?: string;
};
export type ReviewRow = {
  id: string;
  user_id: string;
  lesson_id: string;
  url: string;
  note: string;
  status: string;
  feedback: string | null;
  reviewed_by: string | null;
  revision: number;
  created_at: number;
  updated_at: number;
  name?: string;
  email?: string;
  lesson_title?: string;
};
export type ReviewEventRow = LmsReviewEvent;
export type GrantRow = LmsGrant & { course_title?: string };
export type ReleaseRow = {
  id: string;
  course_id: string;
  lesson_id: string | null;
  version: string;
  title: string;
  body: string;
  important: number;
  created_at: number;
  is_read: number;
};
export type NotificationRow = {
  id: string;
  user_id: string;
  title: string;
  body: string;
  href: string;
  read_at: number | null;
  created_at: number;
};
export type StudentRow = {
  email: string;
  userId: string | null;
  name: string;
  verified: number;
  joinedAt: number | null;
};
