'use client';
import { ArrowUpRight, BookOpen, Code2, LayoutDashboard, LifeBuoy, Bell, Play, ArrowRight, Check, Terminal, GraduationCap } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarGroup, SidebarGroupLabel, SidebarInset, SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
const nav: [LucideIcon,string][] = [[LayoutDashboard,'学习概览'],[BookOpen,'我的课程'],[Code2,'算法练习'],[LifeBuoy,'我的工单'],[Bell,'课程更新']];
export function Academy() {
return <SidebarProvider><Sidebar className="academy-sidebar"><SidebarHeader><a className="brand" href="/"><span className="brand-mark"><Terminal size={21}/></span><span>SDE<span className="brand-light"> Academy</span><small>BUILD. LEARN. SHIP.</small></span></a></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>学习空间</SidebarGroupLabel><SidebarMenu>{nav.map(([Icon,label],i)=><SidebarMenuItem key={label}><SidebarMenuButton isActive={i===0}><Icon size={18}/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><div className="mentor-card"><GraduationCap size={21}/><strong>一步一步，写出好代码。</strong><p>课程、练习和反馈，都在这里。</p></div><div className="profile"><span className="avatar">S</span><div><strong>学习空间</strong><small>SDE 学员</small></div></div></SidebarFooter></Sidebar><SidebarInset className="workspace"><header className="topbar"><div className="flex items-center gap-3"><SidebarTrigger/><span>学习概览</span></div><span className="topbar-note">SDE LEARNING SPACE</span></header><main className="page"><div className="page-heading"><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>专注今天的进步。</h1><p className="muted">从一段代码开始，把知识变成解决问题的能力。</p></div><span className="tag"><span className="status-dot"/>SDE 课程</span></div><section className="continue-card"><div><span className="overline">从这里开始</span><h2>GoMall 后端工程实战</h2><p>沿着真实的交易链路，掌握 Go 后端与系统设计。</p><div className="course-meta"><span>Go / Gin</span><span>系统设计</span><span>配套代码练习</span></div><Button className="primary-light"><Play size={16} fill="currentColor"/>进入第一章<ArrowRight size={16}/></Button></div><div className="terminal-card" aria-hidden="true"><div className="terminal-top"><span/><span/><span/><small>your-next-chapter.go</small></div><pre><em>func</em> main() {'{'}{'\n'}  learn.<b>Understand</b>(){'\n'}  code.<b>Build</b>(){'\n'}  you.<b>Grow</b>(){'\n'}{'}'}</pre><div className="terminal-bottom"><Check size={13}/> Ready for your next step</div></div></section><div className="section-title"><h2>你的学习路径</h2><span className="muted">从基础，到独立交付</span></div><div className="path-grid">{[['01','后端工程基础','用户认证、接口设计与业务建模','Go · Gin · JWT'],['02','交易与资金系统','支付、清算、结算与一致性','事务 · 幂等 · Outbox'],['03','搜索与系统进阶','商品检索、库存和高并发','搜索 · 库存 · 流量治理']].map(([n,title,desc,tags])=><article className="path-card" key={n}><div className="path-top"><span>{n}</span><ArrowUpRight size={20}/></div><h3>{title}</h3><p>{desc}</p><small>{tags}</small><Progress value={0}/></article>)}</div></main></SidebarInset></SidebarProvider>;
}
